<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TblAnggotaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('tbl_anggota')->insert([
            [
                'jabatan' => 'KETUA',
                'nik' => '3215241503730002',
                'nama' => 'JAENUDIN',
                'tanggal_lahir' => '1973-03-15',
                'usia' => 52,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085817135742',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'CICINDE II RT/RW 002/001',
                'kelurahan_desa' => 'CICINDE UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMENANGAN PEMILU',
                'nik' => '3215245004860003',
                'nama' => 'WASRUROH',
                'tanggal_lahir' => '1986-04-10',
                'usia' => 39,
                'jenis_kelamin' => 'P',
                'no_tlp' => '081619933348',
                'pekerjaan' => 'IRT',
                'alamat' => 'JUNGKLANG RT/RW 001/008',
                'kelurahan_desa' => 'JAYAMUKTI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. ORGANISASI DAN KEANGGOTAAN',
                'nik' => '3215241206920001',
                'nama' => 'TAUFIK HIDAYAT',
                'tanggal_lahir' => '1992-06-12',
                'usia' => 33,
                'jenis_kelamin' => 'L',
                'no_tlp' => '081563346634',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'MEKARSARI RT/RW 003/005',
                'kelurahan_desa' => 'JAYAMUKTI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. USAHA MIKRO KECIL DAN MENENGAH',
                'nik' => '3215245606500001',
                'nama' => 'TATI SURYATI',
                'tanggal_lahir' => '1980-06-16',
                'usia' => 45,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085781078584',
                'pekerjaan' => 'IRT',
                'alamat' => 'TALUN ASMAN RT/RW 001/002',
                'kelurahan_desa' => 'TALUNJAYA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. AGAMA DAN MASYARAKAT ADAT',
                'nik' => '3215240101690004',
                'nama' => 'ABDUL MUIZ',
                'tanggal_lahir' => '1969-01-01',
                'usia' => 56,
                'jenis_kelamin' => 'L',
                'no_tlp' => '082298260718',
                'pekerjaan' => 'BURUH',
                'alamat' => 'KRAJAN I RT/RW 002/003',
                'kelurahan_desa' => 'MEKARASIH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. KESEHATAN',
                'nik' => '3215245410880001',
                'nama' => 'NURJANAH',
                'tanggal_lahir' => '1988-10-14',
                'usia' => 37,
                'jenis_kelamin' => 'P',
                'no_tlp' => '083173387459',
                'pekerjaan' => 'IRT',
                'alamat' => 'KALENRAMAN SELATAN RT/RW 001/004',
                'kelurahan_desa' => 'GEMPOL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEREMPUAN DAN ANAK',
                'nik' => '3215244212750001',
                'nama' => 'TATI KURNIATI',
                'tanggal_lahir' => '1975-12-02',
                'usia' => 49,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085602630020',
                'pekerjaan' => 'IRT',
                'alamat' => 'KERAJAN RT/RW 004/002',
                'kelurahan_desa' => 'BANYUASIH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PARIWISATA DAN INDUSTRI KREATIF',
                'nik' => '3215241607750006',
                'nama' => 'YADI PERMANA',
                'tanggal_lahir' => '1975-07-15',
                'usia' => 50,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085817473325',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'BOJONG GIRANG RT/RW 004/003',
                'kelurahan_desa' => 'GEMPOLKOLOT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PERTANIAN, PETERNAKAN, DAN KEMANDIRIAN DESA',
                'nik' => '3215055907010008',
                'nama' => 'HANY LUTHFIANY',
                'tanggal_lahir' => '2001-07-19',
                'usia' => 24,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085776853595',
                'pekerjaan' => 'KARYAWAN',
                'alamat' => 'SAMPORA RT/RW 001/002',
                'kelurahan_desa' => 'KUTARAHARJA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMUDA DAN OLAHRAGA',
                'nik' => '3215141001940003',
                'nama' => 'BUDIMAN',
                'tanggal_lahir' => '1994-01-10',
                'usia' => 31,
                'jenis_kelamin' => 'L',
                'no_tlp' => '083834262657',
                'pekerjaan' => 'BURUH',
                'alamat' => 'CIKALONG RT/RW 002/002',
                'kelurahan_desa' => 'PAMEKARAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUDA BID. KEHUTANAN, AGRARIA DAN TATA RUANG',
                'nik' => '3215090612770003',
                'nama' => 'SHOLEH MAMUN',
                'tanggal_lahir' => '1977-12-06',
                'usia' => 47,
                'jenis_kelamin' => 'L',
                'no_tlp' => '081586932455',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'BK KIARA RT/RW 003/006',
                'kelurahan_desa' => 'GEMBONGAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'SEKRETARIS',
                'nik' => '3215245607730006',
                'nama' => 'IIM BADRIYAH',
                'tanggal_lahir' => '1973-07-16',
                'usia' => 52,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085719156001',
                'pekerjaan' => 'IRT',
                'alamat' => 'CICINDE II RT/RW 001/002',
                'kelurahan_desa' => 'CICINDE UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL SEKRETARIS',
                'nik' => '3215242406870001',
                'nama' => 'IRFAN FIRDAUS',
                'tanggal_lahir' => '1987-06-24',
                'usia' => 38,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085692886448',
                'pekerjaan' => 'BURUH',
                'alamat' => 'KEDAWUNG RT/RW 006/003',
                'kelurahan_desa' => 'TANJUNG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'BENDAHARA',
                'nik' => '3215240201930003',
                'nama' => 'ENJANG JAMAL LATIF',
                'tanggal_lahir' => '1993-01-02',
                'usia' => 32,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085771701460',
                'pekerjaan' => 'BURUH',
                'alamat' => 'CICINDE II RT/RW 001/002',
                'kelurahan_desa' => 'CICINDE UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL BENDAHARA',
                'nik' => '3215245011960006',
                'nama' => 'TATI',
                'tanggal_lahir' => '1976-11-10',
                'usia' => 49,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085711989406',
                'pekerjaan' => 'IRT',
                'alamat' => 'CICINDE I B RT/RW 002/003',
                'kelurahan_desa' => 'CICINDE SELATAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 
            [
                'jabatan' => 'KETUA',
                'nik' => '3215252708800001',
                'nama' => 'AGUS KURNIAWAN',
                'tanggal_lahir' => '1980-08-27',
                'usia' => 45,
                'jenis_kelamin' => 'L',
                'no_tlp' => '08128413369',
                'pekerjaan' => 'BURUH',
                'alamat' => 'PERUM EKAMAS BLOK BI/5 RT/RW 003/005',
                'kelurahan_desa' => 'PANGULAH UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMENANGAN PEMILU',
                'nik' => '3215251006730006',
                'nama' => 'S. SUSWANTO',
                'tanggal_lahir' => '1973-06-10',
                'usia' => 52,
                'jenis_kelamin' => 'L',
                'no_tlp' => '08211281998',
                'pekerjaan' => 'BURUH',
                'alamat' => 'PERUM TAMAN GRIYA PERMAI B 18/18 RT/RW 001/004',
                'kelurahan_desa' => 'PUCUNG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. ORGANISASI DAN KEANGGOTAAN',
                'nik' => '3215251709720004',
                'nama' => 'A. WIRODAT',
                'tanggal_lahir' => '1972-09-17',
                'usia' => 53,
                'jenis_kelamin' => 'L',
                'no_tlp' => '081574409252',
                'pekerjaan' => 'BURUH',
                'alamat' => 'PERUM EKAMAS BLOK BN/21 RT/RW 004/005',
                'kelurahan_desa' => 'PANGULAH UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. USAHA MIKRO KECIL DAN MENENGAH',
                'nik' => '3215256508710005',
                'nama' => 'LUCIA DIAN AVANTY',
                'tanggal_lahir' => '1971-08-25',
                'usia' => 54,
                'jenis_kelamin' => 'P',
                'no_tlp' => '081285746557',
                'pekerjaan' => 'IRT',
                'alamat' => 'P. CIKAMPEK BERBUNGA C5/29 RT/RW 002/007',
                'kelurahan_desa' => 'PANGULAH BARU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. AGAMA DAN MASYARAKAT ADAT',
                'nik' => '3205055407960009',
                'nama' => 'YUNI SOFARANI',
                'tanggal_lahir' => '1996-07-14',
                'usia' => 29,
                'jenis_kelamin' => 'P',
                'no_tlp' => '081210351407',
                'pekerjaan' => 'IRT',
                'alamat' => 'KALIOYOD RT/RW 001/004',
                'kelurahan_desa' => 'WANCIMEKAR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. KESEHATAN',
                'nik' => '3215257006850001',
                'nama' => 'LIA MARLIANI',
                'tanggal_lahir' => '1985-06-30',
                'usia' => 40,
                'jenis_kelamin' => 'P',
                'no_tlp' => '081388723256',
                'pekerjaan' => 'IRT',
                'alamat' => 'SUKASEURI TENGAH RT/RW 002/001',
                'kelurahan_desa' => 'SARIMULYA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEREMPUAN DAN ANAK',
                'nik' => '3215254912790002',
                'nama' => 'DWININGSIH',
                'tanggal_lahir' => '1979-12-09',
                'usia' => 45,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085770927159',
                'pekerjaan' => 'IRT',
                'alamat' => 'TAMAN GRIYA PERMAI BLOK A12 NO 18 RT/RW 005/004',
                'kelurahan_desa' => 'PUCUNG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PARIWISATA DAN INDUSTRI KREATIF',
                'nik' => '3215252604670002',
                'nama' => 'MUS DEES SURYAHADI',
                'tanggal_lahir' => '1967-04-26',
                'usia' => 58,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085779895807',
                'pekerjaan' => 'BURUH',
                'alamat' => 'RAWAMAS INDAH BLOK EE2/05 RT/RW 002/008',
                'kelurahan_desa' => 'JOMIN BARAT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PERTANIAN, PETERNAKAN, DAN KEMANDIRIAN DESA',
                'nik' => '3215253008050002',
                'nama' => 'GUSTI RIZKY HILLYAWAN',
                'tanggal_lahir' => '2005-08-30',
                'usia' => 20,
                'jenis_kelamin' => 'L',
                'no_tlp' => '083110783329',
                'pekerjaan' => 'BURUH',
                'alamat' => 'JL. SIPRUS 6 NO5 REGENCY RT/RW 001/018',
                'kelurahan_desa' => 'CIKAMPEK UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMUDA DAN OLAHRAGA',
                'nik' => '3215251106990001',
                'nama' => 'MUHAMAD NANDANG HENDRIANA',
                'tanggal_lahir' => '1999-06-11',
                'usia' => 26,
                'jenis_kelamin' => 'L',
                'no_tlp' => '083815249717',
                'pekerjaan' => 'BURUH',
                'alamat' => 'SUKAATI TIMUR RT/RW 013/003',
                'kelurahan_desa' => 'JOMIN TIMUR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUDA BID. KEHUTANAN, AGRARIA DAN TATA RUANG',
                'nik' => '3215251702670002',
                'nama' => 'EMAN ANDAYANA',
                'tanggal_lahir' => '1967-02-17',
                'usia' => 58,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085777800651',
                'pekerjaan' => 'BURUH',
                'alamat' => 'GANDOANG RT/RW 002/007',
                'kelurahan_desa' => 'PANGULAH SELATAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'SEKRETARIS',
                'nik' => '3275050304860020',
                'nama' => 'SRI MULYONO',
                'tanggal_lahir' => '1986-04-03',
                'usia' => 39,
                'jenis_kelamin' => 'L',
                'no_tlp' => '083879542797',
                'pekerjaan' => 'BURUH',
                'alamat' => 'PERUM PURI ANGGREK BLOK B.2 NO 1 RT/RW 003/008',
                'kelurahan_desa' => 'WANCIMEKAR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL SEKRETARIS',
                'nik' => '3215252303690004',
                'nama' => 'MUNIF NUR ARIFIN',
                'tanggal_lahir' => '1969-03-23',
                'usia' => 56,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085719451245',
                'pekerjaan' => 'IRT',
                'alamat' => 'PERUM GRIYA PERMAI B22/7 RT/RW 001/004',
                'kelurahan_desa' => 'PUCUNG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'BENDAHARA',
                'nik' => '3215251108670006',
                'nama' => 'RAITA SAPUTRA',
                'tanggal_lahir' => '1967-08-11',
                'usia' => 58,
                'jenis_kelamin' => 'L',
                'no_tlp' => '081398353523',
                'pekerjaan' => 'BURUH',
                'alamat' => 'PERUM EKAMAS PERMAI BC23 RT/RW 003/005',
                'kelurahan_desa' => 'PANGULAH UTARA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL BENDAHARA',
                'nik' => '3215255803060001',
                'nama' => 'SALWA DWI ARYANI',
                'tanggal_lahir' => '2006-03-18',
                'usia' => 19,
                'jenis_kelamin' => 'P',
                'no_tlp' => '082298896188',
                'pekerjaan' => 'IRT',
                'alamat' => 'PURI ANGGREK B3/24 RT/RW 003/008',
                'kelurahan_desa' => 'WANCIMEKAR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 
            [
                'jabatan' => 'KETUA',
                'nik' => '3215142708740001',
                'nama' => 'DADAN IRAWAN',
                'tanggal_lahir' => '1974-08-27',
                'usia' => 51,
                'jenis_kelamin' => 'L',
                'no_tlp' => '083161500690',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'KARAJAN II RT/RW 002/005',
                'kelurahan_desa' => 'JATIWANGI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMENANGAN PEMILU',
                'nik' => '3215141202780002',
                'nama' => 'RISWANTO',
                'tanggal_lahir' => '1978-02-12',
                'usia' => 47,
                'jenis_kelamin' => 'L',
                'no_tlp' => '081287280440',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'BUMI CIKAMPEK BARU D5/4 RT/RW 004/008',
                'kelurahan_desa' => 'BALONGGANDU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. ORGANISASI DAN KEANGGOTAAN',
                'nik' => '3215011206790012',
                'nama' => 'SUWANDI',
                'tanggal_lahir' => '1979-06-12',
                'usia' => 46,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085718394598',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'KARAJAN II RT/RW 001/001',
                'kelurahan_desa' => 'SUKAMEKAR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. USAHA MIKRO KECIL DAN MENENGAH',
                'nik' => '3215145402880002',
                'nama' => 'LUSIYANA',
                'tanggal_lahir' => '1988-02-14',
                'usia' => 37,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085693366552',
                'pekerjaan' => 'IRT',
                'alamat' => 'SUKAMAJU II RT/RW 002/003',
                'kelurahan_desa' => 'JATISARI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. AGAMA DAN MASYARAKAT ADAT',
                'nik' => '3215140406730001',
                'nama' => 'DARSA',
                'tanggal_lahir' => '1973-06-04',
                'usia' => 52,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085894957522',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'KARAJAN RT/RW 003/004',
                'kelurahan_desa' => 'PACING',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. KESEHATAN',
                'nik' => '3215144710900001',
                'nama' => 'NENI NURHAYAI',
                'tanggal_lahir' => '1990-10-07',
                'usia' => 35,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085813380482',
                'pekerjaan' => 'IRT',
                'alamat' => 'KARAJAN I RT/RW 004/002',
                'kelurahan_desa' => 'CIREJAG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEREMPUAN DAN ANAK',
                'nik' => '3215146905040001',
                'nama' => 'SHERLY NAFIKA MEILANI',
                'tanggal_lahir' => '2004-04-29',
                'usia' => 21,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085777785914',
                'pekerjaan' => 'MAHASISWA',
                'alamat' => 'BAKAN NGANTAY RT/RW 002/006',
                'kelurahan_desa' => 'MEKARSARI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PARIWISATA DAN INDUSTRI KREATIF',
                'nik' => '3215144911740002',
                'nama' => 'NOVI YANTINI',
                'tanggal_lahir' => '1974-11-09',
                'usia' => 51,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085716610184',
                'pekerjaan' => 'IRT',
                'alamat' => 'CIKALONG I RT/RW 005/002',
                'kelurahan_desa' => 'CIKALONGSARI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PERTANIAN, PETERNAKAN, DAN KEMANDIRIAN DESA',
                'nik' => '3215140907980001',
                'nama' => 'ROBIYANSAH',
                'tanggal_lahir' => '1998-07-07',
                'usia' => 27,
                'jenis_kelamin' => 'L',
                'no_tlp' => '082114586118',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'TELAR RT/RW 001/001',
                'kelurahan_desa' => 'TELARSARI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMUDA DAN OLAHRAGA',
                'nik' => '3215141601780002',
                'nama' => 'IRMAN',
                'tanggal_lahir' => '1978-01-16',
                'usia' => 47,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085777270353',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'KARAJAN II RT/RW 002/004',
                'kelurahan_desa' => 'KALIJATI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUDA BID. KEHUTANAN, AGRARIA DAN TATA RUANG',
                'nik' => '3215141601780001',
                'nama' => 'ABDURROHMIN',
                'tanggal_lahir' => '1978-01-16',
                'usia' => 47,
                'jenis_kelamin' => 'L',
                'no_tlp' => '089527780935',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'LEMBUR GEDE RT/RW 002/002',
                'kelurahan_desa' => 'JATIRAGAS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'SEKRETARIS',
                'nik' => '3215141907850003',
                'nama' => 'MUKTAR',
                'tanggal_lahir' => '1985-02-08',
                'usia' => 40,
                'jenis_kelamin' => 'L',
                'no_tlp' => '089664981047',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'PULOGEBANG RT/RW 001/002',
                'kelurahan_desa' => 'BARUGBUG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL SEKRETARIS I',
                'nik' => '3215141301900002',
                'nama' => 'RICKI SLAMET JANUAR',
                'tanggal_lahir' => '1990-01-13',
                'usia' => 35,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085776460962',
                'pekerjaan' => 'BURUH',
                'alamat' => 'KERTASARI RT/RW 001/006',
                'kelurahan_desa' => 'BALONGGANDU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL SEKRETARIS II',
                'nik' => '3215140602730003',
                'nama' => 'NATA',
                'tanggal_lahir' => '1973-02-06',
                'usia' => 52,
                'jenis_kelamin' => 'L',
                'no_tlp' => '082125575288',
                'pekerjaan' => 'IRT',
                'alamat' => 'SUKASARI RT/RW 009/004',
                'kelurahan_desa' => 'SITUDAM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'BENDAHARA',
                'nik' => '3215141009790003',
                'nama' => 'ABDUL MANAP',
                'tanggal_lahir' => '1979-09-10',
                'usia' => 46,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085719266976',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'SAWAH BARU RT/RW 003/006',
                'kelurahan_desa' => 'JATIBARU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL BENDAHARA',
                'nik' => '3215144504750004',
                'nama' => 'YUYUN YUNANI',
                'tanggal_lahir' => '1975-04-05',
                'usia' => 50,
                'jenis_kelamin' => 'P',
                'no_tlp' => '081388259244',
                'pekerjaan' => 'IRT',
                'alamat' => 'BUMI CIKAMPEK BARU BLOK K2/08 RT/RW 013/007',
                'kelurahan_desa' => 'BALONGGANDU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 

            [
                'jabatan' => 'KETUA',
                'nik' => '3215130604760001',
                'nama' => 'ENDANG HERMAWAN',
                'tanggal_lahir' => '1976-04-06',
                'usia' => 49,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085212020413',
                'pekerjaan' => 'BURUH',
                'alamat' => 'SENTUL BABAKAN KAUM RT/RW 002/002',
                'kelurahan_desa' => 'CIKAMPEK SELATAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMENANGAN PEMILU',
                'nik' => '3215131808780003',
                'nama' => 'ASEP MULYADI',
                'tanggal_lahir' => '1978-08-18',
                'usia' => 47,
                'jenis_kelamin' => 'L',
                'no_tlp' => '081399599226',
                'pekerjaan' => 'BURUH',
                'alamat' => 'SUKAMANAH TIMUR RT/RW 002/012',
                'kelurahan_desa' => 'CIKAMPEK BARAT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. ORGANISASI DAN KEANGGOTAAN',
                'nik' => '3215136812000003',
                'nama' => 'NANDADILA DESTASYA',
                'tanggal_lahir' => '2000-12-28',
                'usia' => 24,
                'jenis_kelamin' => 'P',
                'no_tlp' => '',
                'pekerjaan' => 'MAHASISWA',
                'alamat' => 'POPONCOL RT/RW 002/003',
                'kelurahan_desa' => 'DAWUAN TENGAH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. USAHA MIKRO KECIL DAN MENENGAH',
                'nik' => '3215251506820009',
                'nama' => 'DODI SUKMANA',
                'tanggal_lahir' => '1982-06-15',
                'usia' => 43,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085894952221',
                'pekerjaan' => 'BURUH',
                'alamat' => 'MEKAR BARU RT/RW 003/001',
                'kelurahan_desa' => 'CIKAMPEK KOTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. AGAMA DAN MASYARAKAT ADAT',
                'nik' => '3215130302010003',
                'nama' => 'WAHYUDIN MUHAMMAD AKBAR',
                'tanggal_lahir' => '2001-02-03',
                'usia' => 24,
                'jenis_kelamin' => 'L',
                'no_tlp' => '0895360660372',
                'pekerjaan' => 'KARYAWAN',
                'alamat' => 'SUKAMAJU RT/RW 003/009',
                'kelurahan_desa' => 'CIKAMPEK TIMUR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. KESEHATAN',
                'nik' => '3215250910910001',
                'nama' => 'ARIEF BUDIMAN',
                'tanggal_lahir' => '1991-10-09',
                'usia' => 34,
                'jenis_kelamin' => 'L',
                'no_tlp' => '',
                'pekerjaan' => 'BURUH',
                'alamat' => 'SASAKSENG RT/RW 015/007',
                'kelurahan_desa' => 'KALIHURIP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEREMPUAN DAN ANAK',
                'nik' => '3215136109710001',
                'nama' => 'SUHARYATI',
                'tanggal_lahir' => '1971-09-21',
                'usia' => 54,
                'jenis_kelamin' => 'P',
                'no_tlp' => '081585348410',
                'pekerjaan' => 'IRT',
                'alamat' => 'GALUR RT/RW 001/003',
                'kelurahan_desa' => 'CIKAMPEK SELATAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PARIWISATA DAN INDUSTRI KREATIF',
                'nik' => '3215131610040001',
                'nama' => 'SAPTA BELLA RASMADAN',
                'tanggal_lahir' => '2004-10-16',
                'usia' => 21,
                'jenis_kelamin' => 'L',
                'no_tlp' => '083839137316',
                'pekerjaan' => 'BURUH',
                'alamat' => 'CIKAMPEK TUA BARAT RT/RW 001/001',
                'kelurahan_desa' => 'CIKAMPEK PUSAKA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PERTANIAN, PETERNAKAN, DAN KEMANDIRIAN DESA',
                'nik' => '3215130912790005',
                'nama' => 'ALI SUPARMAN',
                'tanggal_lahir' => '1979-12-09',
                'usia' => 45,
                'jenis_kelamin' => 'L',
                'no_tlp' => '082249662321',
                'pekerjaan' => 'BURUH',
                'alamat' => 'KAMOJING TIMUR RT 06/02',
                'kelurahan_desa' => 'KAMOJING',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMUDA DAN OLAHRAGA',
                'nik' => '3215130905770004',
                'nama' => 'SURYANTO',
                'tanggal_lahir' => '1977-05-09',
                'usia' => 48,
                'jenis_kelamin' => 'L',
                'no_tlp' => '081220429743',
                'pekerjaan' => 'BURUH',
                'alamat' => 'SENTUL KALER RT/RW 003/002',
                'kelurahan_desa' => 'DAWUAN TIMUR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. KEHUTANAN, AGRARIA DAN TATA RUANG',
                'nik' => '3215134906010001',
                'nama' => 'WULAN MAULIDAH',
                'tanggal_lahir' => '2001-06-09',
                'usia' => 24,
                'jenis_kelamin' => 'P',
                'no_tlp' => '088294262599',
                'pekerjaan' => 'IRT',
                'alamat' => 'MEKARBARU RT/RW 002/001',
                'kelurahan_desa' => 'CIKAMPEK KOTA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'SEKRETARIS',
                'nik' => '3215131304900004',
                'nama' => 'ASIM, ST',
                'tanggal_lahir' => '1980-04-03',
                'usia' => 45,
                'jenis_kelamin' => 'L',
                'no_tlp' => '082111441232',
                'pekerjaan' => 'BURUH',
                'alamat' => 'SENTUL RT/RW 002/002',
                'kelurahan_desa' => 'CIKAMPEK SELATAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL SEKRETARIS',
                'nik' => '3215135510750001',
                'nama' => 'NURMALA NINGSIH',
                'tanggal_lahir' => '1975-10-15',
                'usia' => 50,
                'jenis_kelamin' => 'P',
                'no_tlp' => '081383003530',
                'pekerjaan' => 'IRT',
                'alamat' => 'TEGALWANGI RT/RW 003/007',
                'kelurahan_desa' => 'DAWUAN BARAT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'BENDAHARA',
                'nik' => '3215130407730001',
                'nama' => 'SUKARMAN',
                'tanggal_lahir' => '1973-07-04',
                'usia' => 52,
                'jenis_kelamin' => 'L',
                'no_tlp' => '089518970708',
                'pekerjaan' => 'BURUH',
                'alamat' => 'TEGALWANGI RT/RW 001/007',
                'kelurahan_desa' => 'DAWUAN BARAT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL BENDAHARA',
                'nik' => '3215136708880002',
                'nama' => 'NURHASANAH',
                'tanggal_lahir' => '1988-08-27',
                'usia' => 37,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085781509071',
                'pekerjaan' => 'IRT',
                'alamat' => 'GALUR RT/RW 001/003',
                'kelurahan_desa' => 'CIKAMPEK SELATAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 

            [
                'jabatan' => 'KETUA',
                'nik' => '3215162811800001',
                'nama' => 'EMAN SUHERMAN',
                'tanggal_lahir' => '1980-11-28',
                'usia' => 44,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085717772427',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'TANGKIL PORIS RT/RW 002/002',
                'kelurahan_desa' => 'CITARIK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMENANGAN PEMILU',
                'nik' => '3215162601720001',
                'nama' => 'ENDANG SURYANA',
                'tanggal_lahir' => '1972-01-26',
                'usia' => 53,
                'jenis_kelamin' => 'L',
                'no_tlp' => '081400729712',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'NAGASARI RT/RW 012/006',
                'kelurahan_desa' => 'TIRTASARI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. ORGANISASI DAN KEANGGOTAAN',
                'nik' => '3215160706800002',
                'nama' => 'NANDANG SUMARNA',
                'tanggal_lahir' => '1980-06-07',
                'usia' => 45,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085219273019',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'KARAJAN RT/RW 001/001',
                'kelurahan_desa' => 'KARANGSINOM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. USAHA MIKRO KECIL DAN MENENGAH',
                'nik' => '3215161304820001',
                'nama' => 'KURAISIN',
                'tanggal_lahir' => '1982-04-13',
                'usia' => 43,
                'jenis_kelamin' => 'L',
                'no_tlp' => '089699791116',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'BABAKAN PASIRMALANG RT/RW 002/003',
                'kelurahan_desa' => 'PARAKANMULYA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. AGAMA DAN MASYARAKAT ADAT',
                'nik' => '3215161703890001',
                'nama' => 'SUKANTO',
                'tanggal_lahir' => '1989-03-17',
                'usia' => 36,
                'jenis_kelamin' => 'L',
                'no_tlp' => '08561995004',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'KALENKUPU RT/RW 002/004',
                'kelurahan_desa' => 'BOJONGSARI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. KESEHATAN',
                'nik' => '3215165304030001',
                'nama' => 'DELLA APRIYANTI',
                'tanggal_lahir' => '2003-04-13',
                'usia' => 22,
                'jenis_kelamin' => 'P',
                'no_tlp' => '08811658771',
                'pekerjaan' => 'IRT',
                'alamat' => 'GOMBOL NANGKA RT/RW 005/003',
                'kelurahan_desa' => 'KAMURANG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEREMPUAN DAN ANAK',
                'nik' => '3215165007870006',
                'nama' => 'ADE LASMI',
                'tanggal_lahir' => '1987-07-10',
                'usia' => 38,
                'jenis_kelamin' => 'P',
                'no_tlp' => '089530709257',
                'pekerjaan' => 'IRT',
                'alamat' => 'CIPONDOH RT/RW 002/002',
                'kelurahan_desa' => 'CIPONDOH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PARIWISATA DAN INDUSTRI KREATIF',
                'nik' => '3215162201970003',
                'nama' => 'ZEZEN JANUAR M',
                'tanggal_lahir' => '1997-10-22',
                'usia' => 28,
                'jenis_kelamin' => 'L',
                'no_tlp' => '083815257878',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'CIPONDOH RT/RW 001/001',
                'kelurahan_desa' => 'CIPONDOH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PERTANIAN, PETERNAKAN, DAN KEMANDIRIAN DESA',
                'nik' => '3215160609850001',
                'nama' => 'DEDE RUSNADI',
                'tanggal_lahir' => '1985-09-06',
                'usia' => 40,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085715022339',
                'pekerjaan' => 'BURUH',
                'alamat' => 'BABAKAN CEREME RT/RW 002/001',
                'kelurahan_desa' => 'PARAKAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. PEMUDA DAN OLAHRAGA',
                'nik' => '1606094506830011',
                'nama' => 'MASWATI SUARSIH',
                'tanggal_lahir' => '1983-06-05',
                'usia' => 42,
                'jenis_kelamin' => 'P',
                'no_tlp' => '-',
                'pekerjaan' => 'IRT',
                'alamat' => 'CEPLIK RT/RW 001/001',
                'kelurahan_desa' => 'KERTAWALUYA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL KETUA BID. KEHUTANAN, AGRARIA DAN TATA RUANG',
                'nik' => '3215166812930001',
                'nama' => 'DIAH ANGGRAENI',
                'tanggal_lahir' => '1993-12-28',
                'usia' => 31,
                'jenis_kelamin' => 'P',
                'no_tlp' => '089677488437',
                'pekerjaan' => 'IRT',
                'alamat' => 'PASIRMALANG RT/RW 001/002',
                'kelurahan_desa' => 'PARAKANMULYA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'SEKRETARIS',
                'nik' => '3215161204820006',
                'nama' => 'KRISTIAN MULYANA',
                'tanggal_lahir' => '1982-04-12',
                'usia' => 43,
                'jenis_kelamin' => 'L', // kosong tadi, kuberikan 'L' default logis
                'no_tlp' => '08567454668',
                'pekerjaan' => 'BURUH',
                'alamat' => 'SUKATANI RT/RW 002/005',
                'kelurahan_desa' => 'KARANGJAYA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL SEKRETARIS',
                'nik' => '3215160509820002',
                'nama' => 'DEDE MULYANA',
                'tanggal_lahir' => '1982-09-05',
                'usia' => 43,
                'jenis_kelamin' => 'L',
                'no_tlp' => '085810665576',
                'pekerjaan' => 'WIRASWASTA',
                'alamat' => 'PARAKAN RT/RW 003/001',
                'kelurahan_desa' => 'PARAKAN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'BENDAHARA',
                'nik' => '3215162811900001',
                'nama' => 'ALI MULYANA',
                'tanggal_lahir' => '1990-11-28',
                'usia' => 34,
                'jenis_kelamin' => 'L', // kosong tadi
                'no_tlp' => '089603076507',
                'pekerjaan' => 'BURUH',
                'alamat' => 'GOMBONG TANGKIL RT/RW 001/006',
                'kelurahan_desa' => 'CITARIK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan' => 'WAKIL BENDAHARA',
                'nik' => '3215164106930000',
                'nama' => 'MULYANI GADIS M',
                'tanggal_lahir' => '1993-06-01',
                'usia' => 32,
                'jenis_kelamin' => 'P',
                'no_tlp' => '085780484724',
                'pekerjaan' => 'IRT',
                'alamat' => 'KAMURANG RT/RW 003/002',
                'kelurahan_desa' => 'KAMURANG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
